### PR TITLE
Run as a Docker image, docker compose file, calculate distance if not provided ads-b

### PR DESCRIPTION
**Pull request by diepeterpan**
Provide file to create Docker image where notifier is run every minute using cron.  An example docker-compose file is provided which can be used in e.g. Portainer, the config file, and ads-b decoded files can be mapped in.

When the ads-b decoded files don't contain the distance (like in my case) it can be calculated by providing the base station location in the config file.

Fix minor annoyance where the decimal point is used as a thousands separator and in South Africa that reads then funky.

### CODE REVIEW

**Comment by RundesBalli** [comment]
Hi, thanks for your PR!

I've fixed the formatting issue and created a language based support in the locales.
See here: https://github.com/RundesBalli/adsbTelegramNotifier/commit/58b10546ffef48c52e01350a7bacd72716781540

I wanted to rewrite the script as a systemd service for ages. With your PR you just motivated me to finally do it.

On the Docker topic:
I hate Docker very much. Furthermore, I cannot provide support for Docker, so I would like to politely decline at this point.

On the distance topic:
Why don't you have a distance provided by the decoder? I want to keep the script as simple as possible and unfortunately I am afraid that I would complicate this with an additional (optional!) setting option with coordinates, since experience shows that many people don't read the comments/manuals/docs correctly.

**Comment by diepeterpan** [comment]
> Hi, thanks for your PR!
> 
> I've fixed the formatting issue and created a language-based support in the locales. See here: [58b1054](https://github.com/RundesBalli/adsbTelegramNotifier/commit/58b10546ffef48c52e01350a7bacd72716781540)

Thanks, merged that into my fork, just an FYI, on PHP 8.1 usleep($usleep); gives a 'Deprecated: Implicit conversion from float ...' warning which is easily remedied with e.g. the floor function. - https://php.watch/versions/8.1/deprecate-implicit-conversion-incompatible-float-string 

> 
> I wanted to rewrite the script as a systemd service for ages. With your PR you just motivated me to finally do it.
> 

Thanks, merged that into my fork.

> On the Docker topic: I hate Docker very much. Furthermore, I cannot provide support for Docker, so I would like to politely decline at this point.

Your choice; maybe there are other users who would benefit from it; like me :-)

> 
> On the distance topic: Why don't you have a distance provided by the decoder? I want to keep the script as simple as possible and unfortunately, I am afraid that I would complicate this with an additional (optional!) setting option with coordinates since experience shows that many people don't read the comments/manuals/docs correctly.

I have investigated this for hours on end and it seems to be non-standard; readsb provides the distance but seems to be the only one.  Then the community also seems divided on readsb in its current form and some moving to readsb-protobuf.

In the future, this notifier project might have to look at getting its ADS-B data via TCP using the BEAST format rather than .JSON files.

https://github.com/mikenye/docker-readsb

Deprecation notice
The author of readsb (Mictronics) is no longer developing readsb, and instead all future development efforts will go into the Protocol Buffer version (readsb-protobuf) starting with version v4.0.0 (see [here](https://github.com/Mictronics/readsb#no-longer-under-development)).

I would recommend migrating to the container: [mikenye/readsb-protobuf](https://github.com/mikenye/docker-readsb-protobuf) instead of continuing to use this container.

https://github.com/sdr-enthusiasts/docker-readsb-protobuf

"[Mictronics' readsb-protobuf](https://github.com/Mictronics/readsb-protobuf) Mode-S/ADSB/TIS decoder for RTLSDR, BladeRF, Modes-Beast and GNS5894 devices, running in a docker container.

This version uses Google's protocol buffer for data storage and exchange with web application. Saves on storage space and bandwidth. "

**Comment by RundesBalli** [comment]
> Thanks, merged that into my fork

You're welcome :-)

> just an FYI, on PHP 8.1 usleep($usleep); gives a 'Deprecated: Implicit conversion from float ...' warning which is easily remedied with e.g. the floor function. - https://php.watch/versions/8.1/deprecate-implicit-conversion-incompatible-float-string

Thanks, I have [fixed it](https://github.com/RundesBalli/adsbTelegramNotifier/commit/70ab2b837491d25a8f1224cfb87aa58a94ca6adb) by flooring the value and just to be sure, I converted it into integer (floor returns a float: https://www.php.net/manual/en/function.floor.php)

> Your choice; maybe there are other users who would benefit from it; like me :-)

Unfortunately, this is something I have to accept, since as I mentioned, I can't provide support for Docker issues.

> I have investigated this for hours on end and it seems to be non-standard; readsb provides the distance but seems to be the only one. Then the community also seems divided on readsb in its current form and some moving to readsb-protobuf.

I didn't know until just now that the distance specification seems to be only a specification in the [readsb by wiedehopf](https://github.com/wiedehopf/readsb).
Assuming that:
1. I have understood you correctly and
2. that is so correct, since I have not checked it further.

Furthermore, I linked the wiedehopf-readsb in the [ReadMe.md](https://github.com/RundesBalli/adsbTelegramNotifier/blob/master/README.md#dependencies)

> In the future, this notifier project might have to look at getting its ADS-B data via TCP using the BEAST format rather than .JSON files.

When I look at [this](https://github.com/firestuff/adsb-tools/blob/master/protocols/beast.md] I must say, that I have no desire to read or familiarize myself with it. Sorry.

> Deprecation notice The author of readsb (Mictronics) is no longer developing readsb

I didn't know until just now that anybody seems to use this old software, but I assumed, that everybody today just uses (wiedehopf-)readsb or dump1090-fa.

**Comment by diepeterpan** [comment]
Line 70 must prob. be $runs instead of $run; I get a warning that $runs is not defined on line 84.

**Comment by RundesBalli** [comment]
Fixed, thx

**Pull request closed without merging**
